<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stay Haven Analytics Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            text-align: center;
            color: #007bff;
        }
        h2 {
            color: #343a40;
            margin-top: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            color: #343a40;
        }
        .metrics-grid {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            margin-bottom: 20px;
        }
        .card {
            flex: 1;
            min-width: 200px;
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 5px;
            text-align: center;
        }
        .card h3 {
            font-size: 14px;
            color: #6c757d;
            margin-bottom: 10px;
        }
        .card p {
            font-size: 20px;
            font-weight: bold;
            color: #343a40;
            margin: 0;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <h1>Stay Haven Analytics Report</h1>
    <p style="text-align: center;">Generated on {{ $date }}</p>

    <h2>Key Metrics</h2>
    <div class="metrics-grid">
        <div class="card">
            <h3>Total Transactions</h3>
            <p>{{ number_format($totalTransactions) }}</p>
        </div>
        <div class="card">
            <h3>Total Revenue</h3>
            <p>${{ number_format($totalRevenue, 2) }}</p>
        </div>
        <div class="card">
            <h3>Average Property Price</h3>
            <p>${{ number_format($avgPropertyPrice, 2) }}</p>
        </div>
        <div class="card">
            <h3>Total Landlords</h3>
            <p>{{ number_format($totalLandlords) }}</p>
        </div>
        <div class="card">
            <h3>Total Tenants</h3>
            <p>{{ number_format($totalTenants) }}</p>
        </div>
    </div>

    <h2>User Registrations by Month</h2>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Number of Users</th>
            </tr>
        </thead>
        <tbody>
            @foreach($userRegistrations as $month => $count)
                <tr>
                    <td>{{ $month }}</td>
                    <td>{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Property Price Range Distribution</h2>
    <table>
        <thead>
            <tr>
                <th>Price Range</th>
                <th>Number of Properties</th>
            </tr>
        </thead>
        <tbody>
            @foreach($priceRanges as $range => $count)
                <tr>
                    <td>{{ $range }}</td>
                    <td>{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Payment Method Distribution</h2>
    <table>
        <thead>
            <tr>
                <th>Payment Method</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($paymentMethods as $method => $count)
                <tr>
                    <td>{{ $method }}</td>
                    <td>{{ $count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Monthly Revenue</h2>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Revenue ($)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthlyRevenue as $month => $total)
                <tr>
                    <td>{{ $month }}</td>
                    <td>{{ number_format($total, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Stay Haven Admin Dashboard</p>
    </div>
</body>
</html>